# Generated by Django 4.0 on 2022-01-20 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_tweetcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetcomment',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tweet.tweetmodel'),
        ),
    ]
